### ISSUE TITLE
Fix the incorrect score calculation in Tetris

### ISSUE THREAD

**Issue by jlukacs** [jlukacs/gameboy#2]
The score in Tetris is displaying hex values and is also increasing too fast. This is likely caused by the DAA instruction implementation.

**Comment by tswilliamson** [comment]
I fixed this in my gameboy emulator just today actually. Was because I wasn't handling the memwrite to ROM properly. The game writes to 0x2000 (presumably to activate ram) and if you allow it to write to the ROM at that point you get awarded crazy scores for lines.

**Comment by jlukacs** [comment]
@tswilliamson Thank you! It works now.
